# config/routes.yaml
controllers:
  resource: "../src/Controller/"
  type: attribute
  prefix: /
app.swagger_ui:
  path: /api/doc
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
